---
abstract: 'Updates the Pod for an ORLite generated distribution.'
author:
  - 'Sven Dowideit <sdowideit@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Module::Install::ORLite2Pod
name: Module-Install-ORLite2Pod
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Module::Install: 1.
  ORLite::Pod: 0.11
  Params::Util: 0.1
  perl: 5.6.1
resources:
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Module-Install-ORLite2Pod
version: 1.000
